[package]
name = "glue"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = { version = "4.11.0", optional = true }
futures = "0.3.31"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.15"

[features]
actix = ["actix-web"]
