[package]
name = "auth-dal"
version = "0.1.0"
edition = "2024"

[dependencies]
glue = { version = "0.1.0", path = "../../../glue" }
serde = { version = "1.0.228", features = ["derive"] }
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio", "json"], optional = false }
